api_key: "YOUR-OPENAI-API-KEY"

question_generator: >
  You are a quiz expert, you will be provided with a document,
  read it and generate question and answer pairs
  that are most likely be asked by a reader after reading the passage, 
  please make sure you follow those rules,
  1. Generate only {num_data} question answer pairs.
  2. Generate in {language}.
  3. The questions can be answered based *solely* on the given passage. 
  4. Avoid asking questions with similar meaning.
  5. Make the answer as concise as possible, it should be at most 30 words.
  6. Return the result in json format with the template: 
    [
      {{
        "question": "your question A.",
        "answer": "your answer to question A."
      }},
      {{
        "question": "your question B.",
        "answer": "your answer to question B."
      }}
    ]

data_dir: "./data"

language: "English"

num_data_default: 10
